// Run: node meshvault/generators/pocket-eden/test.cjs. No installation required.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const context=vm.createContext({TextEncoder,TextDecoder,Blob,File,console,setTimeout,clearTimeout});
for(const id of ['eden-three','eden-core','eden-zip','eden-mvpack','eden-assets','eden-audio','eden-io']) {
  const match=html.match(new RegExp('<script id="'+id+'">([\\s\\S]*?)<\\/script>'));assert(match,'Embedded '+id);vm.runInContext(match[1],context);
}
const C=context.EdenCore,A=context.EdenAssets,IO=context.EdenIO,F=context.FFlate;
function verify(mesh,label){
  const p=mesh.positions,ix=mesh.indices,edges=new Map();let volume=0;
  for(let i=0;i<ix.length;i+=3){const [a,b,c]=[ix[i],ix[i+1],ix[i+2]],P=[a,b,c].map(k=>Array.from(p.slice(k*3,k*3+3))),[u,v,w]=P;
    assert(P.flat().every(Number.isFinite),label+' finite vertices');
    const ab=v.map((n,j)=>n-u[j]),ac=w.map((n,j)=>n-u[j]),cross=[ab[1]*ac[2]-ab[2]*ac[1],ab[2]*ac[0]-ab[0]*ac[2],ab[0]*ac[1]-ab[1]*ac[0]];
    assert(Math.hypot(...cross)>1e-12,label+' nondegenerate face '+i/3);
    volume+=(u[0]*(v[1]*w[2]-v[2]*w[1])+u[1]*(v[2]*w[0]-v[0]*w[2])+u[2]*(v[0]*w[1]-v[1]*w[0]))/6;
    for(const [x,y] of [[a,b],[b,c],[c,a]]){const key=Math.min(x,y)+':'+Math.max(x,y),edge=edges.get(key)||[0,0];edge[0]++;edge[1]+=x<y?1:-1;edges.set(key,edge);}
  }
  for(const [key,[count,direction]] of edges){assert.equal(count,2,label+' closed edge '+key);assert.equal(direction,0,label+' outward winding '+key);}assert(volume>0,label+' positive volume');
  const buffer=C.binarySTL(mesh),dv=new DataView(buffer);assert.equal(dv.getUint32(80,true),ix.length/3);assert.equal(buffer.byteLength,84+50*ix.length/3);
  for(let i=0;i<ix.length/3;i++)for(let j=0;j<12;j++)assert(Number.isFinite(dv.getFloat32(84+i*50+j*4,true)),label+' finite STL');
  return volume;
}
async function main(){
  for(const tool of ['raise','carve','level']){
    const gentle=C.makeWorld(71937),full=C.makeWorld(71937),before=Array.from(gentle.heights),sign=tool==='carve'?-1:1;
    for(const [w,strength]of [[gentle,.1],[full,1]]){if(tool==='level')C.flatten(w,0,0,2,before[0]+1,strength);else C.sculpt(w,0,0,2,.1*sign*strength);}
    for(let i=0;i<before.length;i++){
      const gd=gentle.heights[i]-before[i],fd=full.heights[i]-before[i],distance=Math.hypot(gentle.positions[i*3],gentle.positions[i*3+2]);
      assert(Math.abs(gd-fd*.1)<4e-7,tool+' gentle pass changes height proportionally');
      if(distance>=2){assert.equal(gd,0);assert.equal(fd,0);}
      // Near the feathered edge, tiny changes round away in Float32 heights.
      if(Math.abs(fd)>1e-4)assert(Math.abs(gd)>1e-6,tool+' gentle pass reaches the same brush area');
    }
    assert(Math.abs(gentle.heights[0]-before[0])<Math.abs(full.heights[0]-before[0]),tool+' gentle pass is smaller');verify(gentle,tool+' gentle terrain');
  }
  const unchanged=C.makeWorld(71937),initial=Array.from(unchanged.positions);C.flatten(unchanged,0,0,2,5,0);assert.deepEqual(Array.from(unchanged.positions),initial,'Zero level strength has no effect');
  for(const shape of ['island','square','hex'])for(const seed of [71937,0,4294967295]){
    let w=C.makeWorld(seed,{radius:12,rings:72,sectors:192,shape});assert.deepEqual(Array.from(w.positions),Array.from(C.makeWorld(seed,{radius:12,rings:72,sectors:192,shape}).positions));
    const edge=Array.from(w.heights.slice(-w.sectors)),height=C.sample(w,0,0);C.sculpt(w,0,0,1.3,.8);assert(C.sample(w,0,0)>height);C.sculpt(w,w.radius*.98,0,2,-10);assert.deepEqual(Array.from(w.heights.slice(-w.sectors)),edge);
    const before=Array.from(w.heights);C.stroke(w,{x:-3,z:0},{x:3,z:0},.8,(x,z)=>C.paintPath(w,x,z,.8));assert(C.sample(w,0,0,w.paths)>.9);assert(w.heights.some((n,i)=>n<before[i]));
    C.stroke(w,{x:-3,z:0},{x:3,z:0},.8,(x,z)=>C.paintPath(w,x,z,.8,true));assert(w.paths.every(n=>n===0));assert(w.heights.every((n,i)=>Math.abs(n-before[i])<1e-6));
    C.paintPath(w,1,0,.6);const oldTop=Array.from(w.positions.slice(0,w.topCount*3)),oldHeights=Array.from(w.heights),oldPaths=Array.from(w.paths),samples=Array.from({length:20},(_,i)=>{const a=i/20*Math.PI*2,x=Math.cos(a)*10,z=Math.sin(a)*10;return{x,z,height:C.sample(w,x,z),path:C.sample(w,x,z,w.paths)};});const old=w;w=C.expandWorld(w,18);assert.equal(w.radius,12,'Original island size unchanged');assert.equal(w.boundaryRadius,18);assert.deepEqual(Array.from(w.positions.slice(0,oldTop.length)),oldTop,'Every existing terrain vertex stays put');assert.deepEqual(Array.from(w.heights.slice(0,oldHeights.length)),oldHeights);assert.deepEqual(Array.from(w.paths.slice(0,oldPaths.length)),oldPaths);for(const p of samples){assert.equal(C.sample(w,p.x,p.z),p.height,'Sampling stays fixed');assert.equal(C.sample(w,p.x,p.z,w.paths),p.path);}assert(w.heights.slice(old.topCount).every(n=>Math.abs(n-.045)<1e-7),'Expansion starts as empty water');assert(!C.inside(old,14.5,0)&&C.inside(w,14.5,0),'New space is buildable');const outside=C.sample(w,14.5,0);C.sculpt(w,14.5,0,.7,.7);assert(C.sample(w,14.5,0)>outside+.2,'Can raise land beyond the old boundary');assert.throws(()=>C.expandWorld(w,12),'Shrinking cannot silently remove work');verify(w,shape+' expanded terrain');
    const model=C.millimetres(w,440/C.bounds(w).size[0]),b=C.bounds(model);assert(Math.abs(b.size[0]-440)<.0001);assert(Math.abs(b.min[2])<.00001);verify(model,shape+' mm');
    const plan=C.terrainTiles(w,440,220);assert.equal(plan.cols,2,'Exact bed multiples need no extra column');let tiledVolume=0;for(const tile of plan.tiles){tiledVolume+=verify(tile,shape+' tile '+tile.label);assert(tile.sizeMM[0]<=220.0001&&tile.sizeMM[1]<=220.0001);assert(C.bounds(tile).min.every(n=>n>=-.00001));}assert(tiledVolume>0);
    assert(plan.joins.length>0,'Divided landscape has connectors');assert.equal(plan.tiles.reduce((n,t)=>n+t.sockets.length,0),plan.joins.length*2,'Each key has two matching sockets');assert.equal(plan.connector.quantity,plan.joins.length);verify(plan.connector,'Removable key');assert(plan.connector.heightMM<3,'Key has vertical clearance');
    let solidVolume=0;for(let i=0;i<w.topIndexCount;i+=3){const[a,b,c]=[model.indices[i]*3,model.indices[i+1]*3,model.indices[i+2]*3],p=model.positions;solidVolume+=((p[b]-p[a])*(p[c+1]-p[a+1])-(p[b+1]-p[a+1])*(p[c]-p[a]))/2*((p[a+2]+p[b+2]+p[c+2])/3+plan.baseLiftMM);}assert(Math.abs(solidVolume-tiledVolume-plan.joins.length*360)<1,'Only the matching socket volumes are removed from the terrain');
    for(const join of plan.joins)for(const label of [join.a,join.b]){const socket=plan.tiles.find(t=>t.label===label).sockets.find(s=>s.neighbor===(label===join.a?join.b:join.a)&&s.centerMM.every((n,i)=>n===join.centerMM[i]));assert(socket);for(let i=0;i<6;i++){const u=plan.connector.positions[i*3]-8,v=plan.connector.positions[i*3+1]-5;if(label===join.a?u>0:u<0)continue;const point=join.axis===0?[join.centerMM[0]+u,join.centerMM[1]+v]:[join.centerMM[0]+v,join.centerMM[1]+u];assert(socket.planes.every(([nx,ny,d])=>nx*point[0]+ny*point[1]+d>=-1e-5),'Key footprint fits its matching socket');}}
  }
  for(const [type,mesh]of Object.entries(A.meshes))verify(mesh,type);
  for(const type of ['pine','oak']){const profile=A.definitions[type].profile;for(let i=1;i<profile.length;i++)assert((profile[i][1]-profile[i-1][1])/(profile[i][0]-profile[i-1][0])<=Math.tan(50*Math.PI/180),'Tree undersides stay within 50 degrees');}
  for(const [type,parts]of Object.entries(A.printParts))for(const part of parts)verify(part.mesh,type+' '+part.name);
  for(const [type,mesh]of Object.entries(A.meshes)){const clipped=A.clipToTile(mesh,{x0:0,x1:10,y0:-10,y1:10});if(clipped)verify(clipped,type+' seam');}
  const scenePlan=IO.prepareTiles(IO.preset('village'));for(const tile of scenePlan.tiles){assert(tile.sizeMM[0]<=220.001&&tile.sizeMM[1]<=220.001,'Attached scenery stays inside the build area');for(const part of tile.parts)verify(part.mesh,tile.label+' '+part.name);verify(tile,tile.label+' with attached scenery');}
  const crossed=IO.preset('tabletop');crossed.world=C.makeWorld(1,{radius:6,shape:'square',relief:'flat'});crossed.printWidth=160;crossed.items=[{type:'pine',x:-.12,z:1,size:1,rotation:.3,age:1},{type:'oak',x:-.12,z:-.12,size:1,rotation:.5,age:1}];const crossedPlan=IO.prepareTiles(crossed,{bedMM:80});assert(crossedPlan.tiles.some(t=>t.parts.some(p=>p.name.endsWith('seam root'))),'Clipped tree canopies get permanent roots');for(const tile of crossedPlan.tiles)for(const part of tile.parts)verify(part.mesh,'Crossed seam '+part.name);
  for(const kind of ['village','ruins','tabletop','wild']){const state=IO.preset(kind),items=JSON.stringify(state.items);const original=IO.serialise(state);delete original.config.boundaryRadius;assert.equal(C.validateProject(original).world.boundaryRadius,state.world.radius,'Original v2 files still open');state.world=C.expandWorld(state.world,24);assert.equal(JSON.stringify(state.items),items,'Scenery positions and sizes unchanged');C.sculpt(state.world,21,0,1,.7);const saved=IO.serialise(state),restored=C.validateProject(saved);assert.equal(restored.items.length,state.items.length);assert.deepEqual(Array.from(restored.world.positions),Array.from(state.world.positions));assert.deepEqual(Array.from(restored.world.heights),Array.from(state.world.heights));assert.deepEqual(Array.from(restored.world.paths),Array.from(state.world.paths));}
  const largest=C.makeWorld(1,{radius:6,rings:96,sectors:256,boundaryRadius:24});assert.equal(largest.indices.BYTES_PER_ELEMENT,4,'Large boundaries use 32-bit indices');assert(largest.indices.every(n=>n<largest.positions.length/3));verify(largest,'Largest expanded mesh');
  const state=IO.preset('village');state.world=C.expandWorld(state.world,12);C.sculpt(state.world,10.5,0,.8,.6);const pack=await IO.createPack(state,{bedMM:220}),entries=F.unzipSync(new Uint8Array(await pack.arrayBuffer())),manifest=JSON.parse(new TextDecoder().decode(entries['meshvault.models.json']));
  assert.equal(manifest.schema,'meshvault.models');assert.equal(manifest.packType,'project');assert(manifest.models.length>4);assert.equal(manifest.project.title,state.name);
  for(const model of manifest.models){assert(entries[model.relativePath],'Pack model '+model.relativePath);const bytes=entries[model.relativePath];if(model.fileType==='STL'){const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);assert.equal(bytes.length,84+dv.getUint32(80,true)*50);}else{assert.equal(model.fileType,'3MF');const files=F.unzipSync(bytes),xml=new TextDecoder().decode(files['3D/3dmodel.model']);assert(files['[Content_Types].xml']&&files['_rels/.rels']);assert(xml.includes('unit="millimeter"'));assert(xml.includes('<basematerials id="1">'));const objects=[...xml.matchAll(/<object id="(\d+)"[^>]*>([\s\S]*?)<\/object>/g)],ids=objects.map(m=>m[1]),build=xml.match(/<build><item objectid="(\d+)"\/><\/build>/);assert(build&&ids.includes(build[1]));for(const object of objects){const body=object[2];for(const reference of body.matchAll(/<component objectid="(\d+)"\/>/g))assert(ids.includes(reference[1])&&+reference[1]<+object[1],'3MF components reference preceding resources');const vertices=[...body.matchAll(/<vertex x="([^"]+)" y="([^"]+)" z="([^"]+)"\/>/g)];for(const v of vertices)assert(v.slice(1).every(n=>Number.isFinite(Number(n))));for(const t of body.matchAll(/<triangle v1="(\d+)" v2="(\d+)" v3="(\d+)"\/>/g))assert(t.slice(1).every(n=>+n<vertices.length)&&new Set(t.slice(1)).size===3);}assert.equal([...xml.matchAll(/<build>/g)].length,1);}}
  const guide=new TextDecoder().decode(entries['documents/project-build-guide.html']),csv=new TextDecoder().decode(entries['documents/project-scenery-placement.csv']);assert.equal(csv.split('\n').length,state.items.length+1);for(const line of csv.split('\n').slice(1)){const file=line.split(',')[0];assert(entries[file],'Placement points to packaged model '+file);assert(guide.includes(file),'Guide names packaged model '+file);}
  const key=manifest.models.find(m=>m.relativePath.endsWith('terrain-join-key.stl'));assert(key&&guide.includes(key.relativePath),'Connector model and assembly guide agree');const keySettings=JSON.parse(new TextDecoder().decode(entries[key.documentFiles[0]]));assert(keySettings.quantity>0);assert.equal(keySettings.clearanceMM,.2);assert(guide.includes('Removable connectors')&&!guide.includes('no automatic connectors'));
  const one=C.terrainTiles(C.makeWorld(71937),80,220);assert.equal(one.joins.length,0);assert.equal(one.baseLiftMM,0);const tiny=C.terrainTiles(C.makeWorld(1,{radius:24}),120,80,.4);assert(tiny.baseLiftMM>0);assert(tiny.tiles.every(t=>t.positions.every((n,i)=>i%3!==2||n>=0)));assert.equal(tiny.connector.clearanceMM,.4);verify(tiny.connector,'Looser key');for(const t of tiny.tiles)verify(t,'Small scale socket tile');assert.throws(()=>C.terrainTiles(state.world,300,220,0));
  const roundtrip=await IO.readFile(new File([pack],'test.mvpack'));assert.deepEqual(JSON.stringify(IO.serialise(roundtrip)),JSON.stringify(IO.serialise(state)));
  assert.throws(()=>C.validateProject({...IO.serialise(state),items:[{type:'bad',x:0,z:0,size:1,rotation:0}]}));assert.throws(()=>C.applyHeights(state.world,[NaN]));assert.throws(()=>C.stl(state.world,0));assert.throws(()=>C.makeWorld(1,{radius:100}));assert.doesNotThrow(()=>C.stl(C.makeWorld(1),880),'Expanded physical footprint can exceed 600 mm');assert.throws(()=>C.stl(state.world,2401));
  const sources=[];class AudioContext{constructor(){this.currentTime=10;this.state='suspended';this.destination={};}async resume(){this.state='running';}async suspend(){this.state='suspended';}createGain(){return{gain:{value:0,setValueAtTime(){},linearRampToValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){},disconnect(){}};}createOscillator(){const source={frequency:{},connect(){},disconnect(){},start(time){this.startTime=time;},stop(time){this.stopTime=time;if(time===undefined)this.onended?.();}};sources.push(source);return source;}}
  const effects=context.EdenAudio.createEffects(AudioContext);await effects.toggle();assert.equal(sources.length,0,'Enabling sound has no continuous source');effects.play(1);assert.equal(sources.length,2);for(const source of sources){assert(source.stopTime>source.startTime&&source.stopTime-source.startTime<1);source.onended();}assert.equal(effects.activeCount,0,'Effects terminate');await effects.toggle();await effects.toggle();assert.equal(sources.length,2,'Re-enabling sound starts no drone');effects.play();await effects.visibility(true);assert.equal(effects.activeCount,0,'Hidden page stops sound');
  console.log('PASS: combined STL tiles contain scenery; multipart 3MF has aligned named parts, colours, valid mesh indices and resource references; closed clipped scenery and seam roots; tree undersides within 50 degrees; printer-bed limits; paired removable keys and socket volumes; clearance and base thickness; .mvpack guide and quantities; gentler tools; expansion preservation; JSON/.mvpack round-trip; large mesh indices; paths; input validation; finite audio.');
}
main().catch(error=>{console.error(error);process.exitCode=1;});
