// Run: node test.cjs [absolute directory for generated QA samples]
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{
  const e=await import('./engine.js'),out=await import('./exports.js'),imp=await import('./importers.js'),zip=await import('../shared/vendor/fflate.js');
  await e.initKernel(fs.readFileSync(path.join(__dirname,'vendor/manifold.wasm')));
  function closed(mesh){
    const p=mesh.positions,ids=[],lookup=new Map(),edges=new Map();let volume=0;
    for(let i=0;i<p.length;i+=3){assert(Array.from(p.slice(i,i+3)).every(Number.isFinite));const key=Array.from(p.slice(i,i+3)).map(n=>n.toFixed(4)).join(',');if(!lookup.has(key))lookup.set(key,lookup.size);ids.push(lookup.get(key));}
    const roots=Array.from({length:lookup.size},(_,i)=>i),find=i=>{while(roots[i]!==i){roots[i]=roots[roots[i]];i=roots[i];}return i;};
    for(let i=0;i<mesh.indices.length;i+=3){const q=Array.from(mesh.indices.slice(i,i+3));assert(q.every(n=>n<p.length/3));for(let j=0;j<3;j++){const a=ids[q[j]],b=ids[q[(j+1)%3]];assert.notEqual(a,b);roots[find(a)]=find(b);const key=[Math.min(a,b),Math.max(a,b)].join(','),edge=edges.get(key)||{count:0,winding:0};edge.count++;edge.winding+=a<b?1:-1;edges.set(key,edge);}
      const [a,b,c]=q.map(n=>Array.from(p.slice(n*3,n*3+3)));volume+=(a[0]*(b[1]*c[2]-b[2]*c[1])+a[1]*(b[2]*c[0]-b[0]*c[2])+a[2]*(b[0]*c[1]-b[1]*c[0]))/6;
    }assert([...edges.values()].every(n=>n.count===2&&n.winding===0),'Closed, consistently oriented manifold edges');assert.equal(new Set(roots.map((_,i)=>find(i))).size,1,'Every piece is one connected solid');assert(volume>0);return volume;
  }
  let brick;
  for(const type of ['brick','plate','tile','slope','corner','round'])for(const clearance of [-.1,.1,.3]){
    const d=e.definition(type,2,4),mesh=await e.brickMesh(d,clearance);closed(mesh);const b=e.bounds(mesh);assert(Math.abs(b.min[2])<1e-5);assert(Math.abs(b.size[2]-(d.h*3.2+(type==='tile'?0:1.8)))<1e-4);if(type==='brick'&&clearance===.1)brick=mesh;
  }
  for(const [w,l]of [[1,1],[1,8],[8,1],[8,8]])closed(await e.brickMesh(e.definition('brick',w,l),.1));
  await assert.rejects(e.brickMesh(e.definition('brick'),NaN));assert.throws(()=>e.definition('fake'));assert.throws(()=>e.normalise([{positions:[0,0,0,8,0,0,0,8,8],indices:[0,1,1.1]}]));
  function coverage(grid,pieces){const seen=new Uint8Array(grid.occupied.length),[nx,ny,nz]=grid.dimensions;for(const p of pieces)for(const [x,y,z]of e.cells(p.part)){const [u,v]=e.rotateCell(x,y,p.part,p.r),X=p.x+u,Y=p.y+v,Z=p.z+z;assert(X>=0&&X<nx&&Y>=0&&Y<ny&&Z>=0&&Z<nz);const i=(Z*ny+Y)*nx+X;assert.equal(grid.occupied[i],1);assert.equal(seen[i],0,'No overlapping cells');seen[i]=1;}assert.deepEqual(seen,grid.occupied,'Every occupied cell is covered');}
  let seed=731;for(let trial=0;trial<40;trial++){const grid={dimensions:[5,6,7],occupied:new Uint8Array(210)};grid.occupied=grid.occupied.map(()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed%4!==0?1:0;});coverage(grid,e.pack(grid));}
  const block={dimensions:[16,16,12],occupied:new Uint8Array(16*16*12).fill(1)},stack=e.pack(block);coverage(block,stack);assert.equal(e.connections(stack).groups,1,'Alternate courses bridge seams');
  const demo=await e.demoMesh();closed(demo);const set=await e.makeSet([demo],{size:16,clearance:.1});coverage({dimensions:set.dimensions,occupied:set.occupied},set.pieces);assert.equal(set.variants.reduce((n,v)=>n+v.quantity,0),set.pieces.length);assert(set.variants.some(v=>['slope','corner'].includes(v.type)));for(const v of set.variants)closed(v.mesh);
  const raw=out.plateSTL(brick),roundtrip=imp.readSTL(raw)[0];assert.equal(roundtrip.indices.length,brick.indices.length);assert.deepEqual(e.bounds(roundtrip),e.bounds(brick));assert.throws(()=>imp.readSTL(new Uint8Array([1,2,3])));
  const vessel=await import('../vessels/geometry.js'),triangle={positions:[0,0,0,1,0,0,0,2,0],indices:[0,1,2]},vesselRoundtrip=imp.readSTL(vessel.binarySTL(triangle))[0];assert.deepEqual(Array.from(vesselRoundtrip.positions,n=>n||0),[0,0,0,1,0,0,0,0,2],'Existing Y-up vessel export is preserved');
  const three=zip.unzipSync(new Uint8Array(await out.assembled3MF(set).arrayBuffer())),xml=zip.strFromU8(three['3D/3dmodel.model']);assert.equal((xml.match(/<item /g)||[]).length,set.pieces.length);assert.equal((xml.match(/<object /g)||[]).length,set.variants.length);assert(xml.includes('unit="millimeter"'));assert(xml.includes('<basematerials'));
  const thumbnail=new Blob([Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+j6X8AAAAASUVORK5CYII=','base64')],{type:'image/png'}),settings={size:16,clearance:.1},kit=await out.exportSet(set,{name:'Lighthouse',settings,thumbnail}),pack=await out.exportSet(set,{name:'Lighthouse',settings,thumbnail,meshvault:true}),files=zip.unzipSync(new Uint8Array(await pack.arrayBuffer())),manifest=JSON.parse(zip.strFromU8(files['meshvault.models.json']));assert.equal(manifest.packType,'project');assert.equal(manifest.models.length,set.variants.length);assert(manifest.project.documentFiles.some(n=>n.endsWith('assembly-guide.html')));assert(manifest.models.every(m=>files[m.relativePath]&&files[m.thumbnailFile]));assert(out.guideHTML(set,'<safe>',settings).includes('&lt;safe&gt;'));
  // A tiny standards-based faceted STEP box also exercises the real OCCT reader.
  let entities=[],next=1,add=s=>{const id=next++;entities.push(`#${id}=${s};`);return id;};
  const coords=[[0,0,0],[16,0,0],[16,16,0],[0,16,0],[0,0,16],[16,0,16],[16,16,16],[0,16,16]],points=coords.map(p=>add(`CARTESIAN_POINT('',(${p.map(n=>n+'.').join(',')}))`));
  const faces=[[0,3,2,1],[4,5,6,7],[0,1,5,4],[1,2,6,5],[2,3,7,6],[3,0,4,7]].map(q=>{const loop=add(`POLY_LOOP('',(${q.map(i=>'#'+points[i]).join(',')}))`),bound=add(`FACE_OUTER_BOUND('',#${loop},.T.)`),a=coords[q[1]].map((n,i)=>(n-coords[q[0]][i])/16),b=coords[q[2]].map((n,i)=>(n-coords[q[1]][i])/16),normal=[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],direction=add(`DIRECTION('',(${normal.map(n=>n+'.').join(',')}))`),reference=add(`DIRECTION('',(${a.map(n=>n+'.').join(',')}))`),axis=add(`AXIS2_PLACEMENT_3D('',#${points[q[0]]},#${direction},#${reference})`),plane=add(`PLANE('',#${axis})`);return add(`FACE_SURFACE('',(#${bound}),#${plane},.T.)`);});
  const shell=add(`CLOSED_SHELL('',(${faces.map(i=>'#'+i).join(',')}))`),brep=add(`FACETED_BREP('box',#${shell})`),length=add('(LENGTH_UNIT()NAMED_UNIT(*)SI_UNIT(.MILLI.,.METRE.))'),angle=add('(NAMED_UNIT(*)PLANE_ANGLE_UNIT()SI_UNIT($,.RADIAN.))'),context=add(`(GEOMETRIC_REPRESENTATION_CONTEXT(3)GLOBAL_UNIT_ASSIGNED_CONTEXT((#${length},#${angle}))REPRESENTATION_CONTEXT('',''))`),representation=add(`FACETED_BREP_SHAPE_REPRESENTATION('',(#${brep}),#${context})`);
  const app=add("APPLICATION_CONTEXT('configuration controlled 3d designs of mechanical parts and assemblies')"),productContext=add(`PRODUCT_CONTEXT('',#${app},'mechanical')`),product=add(`PRODUCT('box','box','',(#${productContext}))`),formation=add(`PRODUCT_DEFINITION_FORMATION('','',#${product})`),definitionContext=add(`PRODUCT_DEFINITION_CONTEXT('part definition',#${app},'design')`),productDefinition=add(`PRODUCT_DEFINITION('','',#${formation},#${definitionContext})`),shape=add(`PRODUCT_DEFINITION_SHAPE('','',#${productDefinition})`);add(`SHAPE_DEFINITION_REPRESENTATION(#${shape},#${representation})`);
  const step=`ISO-10303-21;\nHEADER;\nFILE_DESCRIPTION(('Brick Foundry check'),'2;1');\nFILE_NAME('box.step','2026-01-01T00:00:00',('Xalies'),(''),'','','');\nFILE_SCHEMA(('CONFIG_CONTROL_DESIGN'));\nENDSEC;\nDATA;\n${entities.join('\n')}\nENDSEC;\nEND-ISO-10303-21;`;
  const occt=await require('./vendor/occt-import-js.js')({wasmBinary:fs.readFileSync(path.join(__dirname,'vendor/occt-import-js.wasm'))}),read=occt.ReadStepFile(new Uint8Array(Buffer.from(step)),{linearUnit:'millimeter'});assert(read.success&&read.meshes.length,'STEP importer reads generated box');const m=read.meshes[0];assert(e.bounds({positions:m.attributes.position.array}).size.every(n=>Math.abs(n-16)<1e-5));
  if(process.argv[2]){const dir=path.resolve(process.argv[2]);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'lighthouse.stl'),out.plateSTL(demo));fs.writeFileSync(path.join(dir,'lighthouse.3mf'),new Uint8Array(await out.create3MF(demo).arrayBuffer()));fs.writeFileSync(path.join(dir,'box.step'),step);fs.writeFileSync(path.join(dir,'assembled.3mf'),new Uint8Array(await out.assembled3MF(set).arrayBuffer()));fs.writeFileSync(path.join(dir,'print-kit.zip'),new Uint8Array(await kit.arrayBuffer()));fs.writeFileSync(path.join(dir,'lighthouse.mvpack'),new Uint8Array(await pack.arrayBuffer()));}
  console.log(`Passed: closed meshes and fit extremes; exact grid coverage; STL round-trip; STEP units; 3MF instances; ${set.pieces.length}-piece kit and .mvpack project.`);
})().catch(error=>{console.error(error);process.exitCode=1;});
