import {bracketMesh} from './geometry.js';
import {plateSTL} from '../gridfinity/plates.js';
import {create3MF,createPackage,canvasThumbnail,saveFile} from '../shared/mvpack.js';
const form=document.querySelector('#settings'),creator=document.querySelector('#creator'),host=document.querySelector('#viewer'),status=document.querySelector('#status'),pack=document.querySelector('#mvpack'),download=document.querySelector('#download'),format=document.querySelector('#format');
let renderer,scene,camera,controls,mesh,current,revision=0,timer;
const escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function url(value){if(!value.trim())return '';const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw new Error('Use HTTPS links without a username or password.');return u.href;}
function attribution(validate=true){if(validate&&!creator.reportValidity())throw new Error('Check your creator details.');return {author:creator.elements.author.value.trim(),authorUrl:url(creator.elements.authorUrl.value),authorSupport:url(creator.elements.authorSupport.value),donation:url(creator.elements.donation.value),relatedUrl:url(creator.elements.relatedUrl.value),youtube:youtubeId(creator.elements.youtube.value)};}
function youtubeId(value){if(!value.trim())return '';const u=new URL(url(value)),host=u.hostname.toLowerCase();let id;if(host==='youtu.be')id=u.pathname.slice(1).split('/')[0];else if(['youtube.com','www.youtube.com','m.youtube.com','youtube-nocookie.com','www.youtube-nocookie.com'].includes(host)){const parts=u.pathname.split('/').filter(Boolean);id=['embed','shorts'].includes(parts[0])?parts[1]:u.searchParams.get('v');}if(!/^[a-zA-Z0-9_-]{11}$/.test(id||''))throw new Error('Enter a YouTube watch, share, Shorts or embed URL.');return id;}
function description(snapshot,a){return `<h2>${escape(snapshot.settings.title)}</h2><p>Custom L-shaped mounting bracket, designed by <strong>${escape(a.author)}</strong>${a.authorUrl?` · <a href="${escape(a.authorUrl)}">Creator profile</a>`:''}.</p><p>${snapshot.settings.length} × ${snapshot.settings.height} mm legs, ${snapshot.settings.width} mm wide and ${snapshot.settings.thickness} mm thick. ${snapshot.settings.holes} holes per leg, ${snapshot.settings.diameter} mm bore diameter. Outer edge chamfer: ${snapshot.settings.edgeChamfer} mm; hole-opening chamfer: ${snapshot.settings.holeChamfer} mm (45°).</p>${a.authorSupport?`<p><a href="${escape(a.authorSupport)}">Support ${escape(a.author)}</a></p>`:''}${a.relatedUrl?`<p><a href="${escape(a.relatedUrl)}">More about this project</a></p>`:''}${a.youtube?`<h3>Video guide</h3><div class="video-embed"><iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/${a.youtube}" title="YouTube video guide" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="encrypted-media; picture-in-picture; fullscreen" allowfullscreen></iframe></div><p><a href="https://www.youtube.com/watch?v=${a.youtube}">Watch the video on YouTube</a></p>`:''}<p>Generated with Bracket Works. Check the printed fit, corner and fastening before use; no rated load.</p>`;}
function showDescription(){if(!current)return;try{document.querySelector('#description').innerHTML=description(current,attribution(false));}catch(e){document.querySelector('#description').textContent=e.message;}}
function credit(){document.querySelector('#credit-author').textContent=creator.elements.author.value||'Your name';const link=document.querySelector('#credit-support');try{const href=url(creator.elements.donation.value);link.hidden=!href;link.href=href;}catch{link.hidden=true;}showDescription();}
function render(){renderer.render(scene,camera);}
function resetView(){if(!mesh)return;const bounds=new THREE.Box3().setFromObject(mesh),centre=bounds.getCenter(new THREE.Vector3()),size=bounds.getSize(new THREE.Vector3()),d=Math.max(size.x,size.y,size.z)*1.7/Math.min(1,camera.aspect);camera.position.set(centre.x+d,centre.y+d*.7,centre.z+d);controls.target.copy(centre);controls.update();render();}
async function update(){const version=++revision;current=null;pack.disabled=download.disabled=true;try{form.elements.edge.disabled=form.elements.holes.value==='1';if(!form.reportValidity())throw new Error('Check the bracket dimensions.');const settings=Object.fromEntries(new FormData(form));for(const name of ['length','height','width','thickness','diameter','edge','holes','edgeChamfer','holeChamfer'])settings[name]=Number(form.elements.namedItem(name).value);const geometry=bracketMesh(settings);if(mesh){scene.remove(mesh);mesh.geometry.dispose();mesh.material.dispose();}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(geometry.positions.flatMap((_,i)=>i%3===0?[geometry.positions[i],geometry.positions[i+2],-geometry.positions[i+1]]:[]),3));g.setIndex(geometry.indices);g.computeVertexNormals();mesh=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:'#f49b73',roughness:.6,flatShading:true}));scene.add(mesh);resetView();const thumbnail=await canvasThumbnail(renderer.domElement,'#28232e');if(version!==revision)return;current={settings,geometry,thumbnail,files:{
  '3mf':new File([create3MF(geometry)],'custom-bracket.3mf',{type:'model/3mf'}),
  'stl':new File([plateSTL(geometry)],'custom-bracket.stl',{type:'model/stl'})
}};showDescription();pack.disabled=download.disabled=false;status.textContent='Your bracket is ready.';document.querySelector('#dimensions').textContent=`${settings.length} × ${settings.height} mm legs · ${settings.width} mm wide · ${settings.holes*2} holes`;document.querySelector('#package-contents').textContent='custom-bracket.mvpack\n├── custom-bracket.'+format.value+'\n├── meshvault.model.json\n├── images/thumbnail.png (16:9)\n└── documents/generator-settings.json';}catch(error){status.textContent=error.message;}}
try{renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor('#28232e');host.append(renderer.domElement);scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.1,5000);controls=new THREE.OrbitControls(camera,renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x645368,1));const light=new THREE.DirectionalLight(0xffeddc,.85);light.position.set(100,250,150);scene.add(light);new ResizeObserver(()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();resetView();}).observe(host);controls.addEventListener('change',render);update();}catch(e){status.textContent=`3D preview unavailable: ${e.message}`;}
form.addEventListener('submit',e=>e.preventDefault());creator.addEventListener('submit',e=>e.preventDefault());form.addEventListener('input',()=>{revision++;current=null;pack.disabled=download.disabled=true;clearTimeout(timer);timer=setTimeout(update,150);});creator.addEventListener('input',credit);format.addEventListener('change',update);document.querySelector('#reset-view').addEventListener('click',resetView);
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>{const values={compact:[50,40,25,4,4,10],wide:[80,65,50,6,5,15],tall:[60,100,30,6,4.5,12]}[b.dataset.preset];['length','height','width','thickness','diameter','edge'].forEach((n,i)=>form.elements.namedItem(n).value=values[i]);form.elements.holes.value=2;clearTimeout(timer);update();}));
async function exportModel(meshvault){if(!current)return;const snapshot=current;pack.disabled=download.disabled=true;try{const file=snapshot.files[format.value];if(!meshvault){saveFile(file,file.name);return;}const a=attribution();if(!a.author)throw new Error('Enter the model author.');const notes={orientation:'Print on the L-shaped side',layerHeightMm:.2,perimeters:4,infillPercent:40,bridges:'Inspect horizontal hole bridges in the slicer',loadRating:'Prototype: no tested load rating'};saveFile(await createPackage({file,title:snapshot.settings.title,author:a.author,authorUrl:a.authorUrl,generatorName:'Bracket Works',exportDonationUrl:a.donation,sourceUrl:'https://xalies.github.io/generators/brackets/',summary:'A custom mounting bracket with personalised creator credit.',tags:['bracket','mounting','generated'],settings:snapshot.settings,printNotes:JSON.stringify(notes),thumbnail:snapshot.thumbnail,descriptionHtml:description(snapshot,a)}), 'custom-bracket.mvpack');status.textContent=`Exported with ${a.author} as the model author.`;}catch(e){status.textContent=`Export failed: ${e.message}`;}finally{pack.disabled=download.disabled=!current;}}
pack.addEventListener('click',()=>exportModel(true));download.addEventListener('click',()=>exportModel(false));
